{{- if .Values.wasmSandbox.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simulator.fullname" . }}-wasm-sandbox
  labels:
    {{- include "simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: wasm-sandbox
spec:
  type: {{ .Values.wasmSandbox.service.type }}
  ports:
    - port: {{ .Values.wasmSandbox.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simulator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wasm-sandbox
{{- end }}
